using System;
using System.Text.RegularExpressions;

namespace CodeMetricsLoader.CodeCoverage
{
    /// <summary>
    /// Represents class generated by ReportGenerator, basically class name and namespace.
    /// </summary>
    public class CodeCoverageClass
    {
        public string ClassName { get; private set; }
        public string Namespace { get; private set; }

        public static CodeCoverageClass Parse (string fullClassName)
        {
            if (string.IsNullOrEmpty(fullClassName))
            {
                throw new ArgumentException(nameof(fullClassName));
            }
            
            var result = new CodeCoverageClass();
            
            int index = fullClassName.LastIndexOf('.');
            if (index == -1)
            {
                result.ClassName = fullClassName;
            }
            else
            {
                result.Namespace = fullClassName.Substring(0, index);
                result.ClassName = fullClassName.Substring(index + 1);    
            }
            return result;
        }
    }
}